---
title: "TopGolf_Speedway_Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(plyr)
colors_df <- c("#3d5a80", "#e56b6f")

tg_data <- read_csv("t.test.csv")

mu <- ddply(tg_data, "update", summarise, grp.mean=mean(decimal))

# Use semi-transparent fill
ggplot(tg_data, aes(x=decimal, fill=update)) +
  geom_density(alpha=0.4) +
  geom_vline(data=mu, aes(xintercept=grp.mean, color=update),
              linetype="dashed") +
  #scale_x_() +
 expand_limits(x=0, y=0) +
  scale_fill_manual(values = colors_df) + 
  scale_color_manual(values = colors_df) +
  labs(x = "Practice Ball Percentage", y = "", title = "Practice Balls - Speedway Update; Density Plot", subtitle = "") +
  theme_minimal() +
  theme(legend.title = element_blank(), legend.position = c(.9,.9), axis.text.y = element_blank(), axis.line = element_line(), panel.grid = element_blank())



#ggplot(tg_data, aes(x=decimal, fill=update)) +
#  geom_density(alpha=0.4) +
#  geom_histogram(aes(y=..density..), alpha=0.5, 
#               position="identity")
```

```{r}
tg_data %>% 
  t.test(decimal ~ update, data = ., conf.level = 0.95)

tg_data %>%
  filter(update == "pre-update") %>%
  select(decimal) %>%
  var()

tg_data %>%
  filter(update != "pre-update") %>%
  select(decimal) %>%
  var()
```

