---
title: "r codes helper"
output: html_notebook
---

```{r}
sa<-c(10,11,12,9,9,11)
sd<-c(9,9,0,8,9,7,9)

# little s or standard deviation sa
sd(sa) 

# creates the function to get the standard errors mean
standard_error <- function(x) sd(x) / sqrt(length(x)) 

# gets the standard error sample mean for sa
standard_error (sa) 

# gets the 95% confidence interval for sa
t.test(sa, conf.level=0.95) 

# on one sample t.test for sa, Mu changes
t.test(sa,mu=10)  

# gets the mean of sa
mean(sa) 

# two sample t.
t.test(sa,sd)  

```

```{r}
ach<-c(28,27,25,24,24,23,23,23,22,21,19,18,17,15,13)
aff<-c(12,10,14,18,11,15,16,19,22,20,18,24,25,23,26)

# computes the correlation coefficient(r)
cor(ach,aff)  

# fit a regression model note where “y” goes.
regmodel=lm(aff~ach)  

relation <- lm(aff~ach)

print(relation)

```

```{r}
# command chi sq.
chisqprob2<-matrix(c(9,26,31,34),ncol=2,byrow=T) 

colnames(chisqprob2)<-c("2","5")

rownames(chisqprob2)<-c("Joiners","NonJoiners")

chisqprob2<-as.table(chisqprob2)

chisqprob2

chisq.test (chisqprob2)

```
